import FWCore.ParameterSet.Config as cms

checkflattening = cms.EDAnalyzer("CheckFlattening",
                                 vertexTag_=cms.InputTag("hiSelectedVertex"),
                                 centralityTag_=cms.InputTag("hiCentrality"),
                                 inputPlanesTag_ = cms.InputTag("hiEvtPlane","recoLevel"),
                                 HFEtScale_ = cms.untracked.int32(3800),
                                 FlatOrder_ = cms.untracked.int32(9),
                                 NumFlatBins_ = cms.untracked.int32(40),
                                 CentBinCompression_ = cms.untracked.int32(5),
                                 Branch_Cent = cms.untracked.bool(True),
                                 Branch_Vtx = cms.untracked.bool(True),
                                 Branch_epang = cms.untracked.bool(True),
                                 Branch_epang_orig = cms.untracked.bool(False),
                                 Branch_epang_RecenterOnly = cms.untracked.bool(False),
                                 Branch_NoWgt = cms.untracked.bool(False),
                                 Branch_epsin = cms.untracked.bool(False),
                                 Branch_epcos = cms.untracked.bool(False),
                                 Branch_epsin_orig = cms.untracked.bool(False),
                                 Branch_epcos_orig = cms.untracked.bool(False),
                                 Branch_epsin_RecenterOnly = cms.untracked.bool(False),
                                 Branch_epcos_RecenterOnly = cms.untracked.bool(False),
                                 Branch_epsin_NoWgt = cms.untracked.bool(False),
                                 Branch_epcos_NoWgt = cms.untracked.bool(False),
                                 Branch_sumw = cms.untracked.bool(False),
                                 Branch_sumw2 = cms.untracked.bool(False),
                                 Branch_sumPtOrEt = cms.untracked.bool(False),
                                 Branch_sumPtOrEt2 = cms.untracked.bool(False),
                                 Branch_qx = cms.untracked.bool(True),
                                 Branch_qy = cms.untracked.bool(True),
                                 Branch_q = cms.untracked.bool(True),
                                 Branch_mult = cms.untracked.bool(True),
                                 Branch_Run = cms.untracked.bool(True),
                                 Branch_Rescor = cms.untracked.bool(True),
                                 Branch_RescorErr = cms.untracked.bool(True)
)
