import FWCore.ParameterSet.Config as cms

hiEvtPlaneFlatCalib = cms.EDAnalyzer('HiEvtPlaneFlatCalib',
                                     vertexTag_=cms.InputTag("hiSelectedVertex"),
                                     centralityTag_=cms.InputTag("hiCentrality"),
                                     caloTag_=cms.InputTag("towerMaker"),
                                     trackTag_=cms.InputTag("hiGeneralTracks"),                           
                                     inputPlanesTag_ = cms.InputTag("hiEvtPlane","recoLevel"),
                                     centScale_ = cms.untracked.double(5000.),
                                     genFlatPsi_ = cms.untracked.bool(True),
                                     FlatOrder_ = cms.untracked.int32(9),
                                     NumFlatCentBins_ = cms.untracked.int32(50),
                                     CentBinCompression_ = cms.untracked.int32(4),
                                     useOffsetPsi_ = cms.untracked.bool(True),
                                     useECAL_ = cms.untracked.bool(True),
                                     useHCAL_ = cms.untracked.bool(True),
                                     useTrackPtWeight_ = cms.untracked.bool(True),
                                     useMomentumCorrV1_ = cms.untracked.bool(True),
                                     minet_ = cms.untracked.double(0.3),
                                     maxet_ = cms.untracked.double(80.0),
                                     effm_ = cms.untracked.double(0.0),
                                     minpt_ = cms.untracked.double(0.3),
                                     maxpt_ = cms.untracked.double(2.6),
                                     minvtx_ = cms.untracked.double(-25.),
                                     maxvtx_ = cms.untracked.double(25.),
                                     dzerr_ = cms.untracked.double(10.),
                                     chi2_ = cms.untracked.double(40.),
                                     Noffmin_ = cms.untracked.int32 (-1),
                                     Noffmax_ = cms.untracked.int32 (10000),
                                     minrun_ = cms.untracked.int32 (210490),
                                     maxrun_ = cms.untracked.int32 (211631)
                                     )
